// <auto-generated />
namespace Care.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Null2DateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Null2DateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201802021853200_Null2DateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
